/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete_Peliculas;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MARTHA
 */
public class Peliculas extends javax.swing.JFrame {

    /**
     * Creates new form Peliculas
     */
    public Peliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        ImagenPelicula1 = new javax.swing.JLabel();
        GeneroPelicula1 = new javax.swing.JLabel();
        ImagenPelicula2 = new javax.swing.JLabel();
        EtiquetaPelicula2 = new javax.swing.JLabel();
        GeneroPelicula2 = new javax.swing.JLabel();
        TituloPelicula1 = new javax.swing.JLabel();
        EtiquetaPelicula3 = new javax.swing.JLabel();
        GeneroPelicula3 = new javax.swing.JLabel();
        ImagenPelicula3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peliculas");

        Panel.setLayout(new java.awt.GridBagLayout());

        ImagenPelicula1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Peliculas\\src\\main\\java\\Imagenes\\05691994812624d843e2d320faa95cc6.jpg")); // NOI18N
        ImagenPelicula1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenPelicula1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        Panel.add(ImagenPelicula1, gridBagConstraints);

        GeneroPelicula1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GeneroPelicula1.setText("Genero: Accion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        Panel.add(GeneroPelicula1, gridBagConstraints);

        ImagenPelicula2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Peliculas\\src\\main\\java\\Imagenes\\20af79db862fee8e38d9435a363edda3.jpg")); // NOI18N
        ImagenPelicula2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenPelicula2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        Panel.add(ImagenPelicula2, gridBagConstraints);

        EtiquetaPelicula2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiquetaPelicula2.setText("Titulo: Avengers I.W");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        Panel.add(EtiquetaPelicula2, gridBagConstraints);

        GeneroPelicula2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GeneroPelicula2.setText("Genero: Accion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        Panel.add(GeneroPelicula2, gridBagConstraints);

        TituloPelicula1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloPelicula1.setText("Titulo: Stranger Things");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 13);
        Panel.add(TituloPelicula1, gridBagConstraints);

        EtiquetaPelicula3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiquetaPelicula3.setText("Titulo: El Prisionero Espacial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        Panel.add(EtiquetaPelicula3, gridBagConstraints);

        GeneroPelicula3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GeneroPelicula3.setText("Genero: Ciencia Ficcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        Panel.add(GeneroPelicula3, gridBagConstraints);

        ImagenPelicula3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Peliculas\\src\\main\\java\\Imagenes\\download.jpg")); // NOI18N
        ImagenPelicula3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenPelicula3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        Panel.add(ImagenPelicula3, gridBagConstraints);

        jScrollPane1.setViewportView(Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenPelicula1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenPelicula1MouseClicked
        try {
            try {
                // TODO add your handling code here:

                Desktop.getDesktop().browse(new URI("https://www.netflix.com/co/title/80057281"));
            } catch (IOException ex) {
                Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ImagenPelicula1MouseClicked

    private void ImagenPelicula3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenPelicula3MouseClicked
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://www.cine-calidad.com/solitary-2021/"));
            } catch (IOException ex) {
                Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ImagenPelicula3MouseClicked

    private void ImagenPelicula2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenPelicula2MouseClicked
        // TODO add your handling code here:
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://www.cine-calidad.com/avengers-infinity-war-2018/"));
            } catch (IOException ex) {
                Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ImagenPelicula2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaPelicula2;
    private javax.swing.JLabel EtiquetaPelicula3;
    private javax.swing.JLabel GeneroPelicula1;
    private javax.swing.JLabel GeneroPelicula2;
    private javax.swing.JLabel GeneroPelicula3;
    private javax.swing.JLabel ImagenPelicula1;
    private javax.swing.JLabel ImagenPelicula2;
    private javax.swing.JLabel ImagenPelicula3;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TituloPelicula1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
